diagnose_driver

diff --git a/macos/CI/diagnose_driver b/macos/CI/diagnose_driver
--- a/macos/CI/diagnose_driver
+++ b/macos/CI/diagnose_driver
@@ -1,5 +1,10 @@
 #!/bin/bash 
 # set -xv
 . driver_info
-[[ -d "${DRIVER_BUNDLE_PATH}" ]] || echo 2>&1 "Could not find kext bundle ${DRIVER_BUNDLE_PATH}" && exit 1
-2>/dev/null kmutil print-diagnostics -pv "${DRIVER_BUNDLE_PATH}"
+if [[ -d "${DRIVER_BUNDLE_PATH}" ]] 
+then
+    2>/dev/null kmutil print-diagnostics -pv "${DRIVER_BUNDLE_PATH}"
+else
+    echo 2>&1 "Could not find kext bundle ${DRIVER_BUNDLE_PATH}"
+    exit 1
+fi
